services:
  fronius-meter-emulation:
    restart: always
    build:
      context: .
    ports:
      - "5502:5502"
    healthcheck:
      test: netstat -an | grep 5502 > /dev/null; if [ 0 != $? ]; then exit 1; fi;
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
