name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo build
        run: cargo build --verbose
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
